markdown: kramdown
# Project
project: OpenStack Deployment and Operations Guide
lead: "A guide for deploying OpenStack with NetApp"
public_url: http://netapp.github.io/openstack-deploy-ops-guide

# GitHub
repo: http://github.com/netapp/openstack-deploy-ops-guide

# Company
www: http://www.netapp.com
ntapos: http://www.netapp.com/openstack
docs: http://docs.openstack.org

# Social
github: http://github.com/netapp
twitter: http://twitter.com/openstacknetapp

# Server
permalink: pretty
exclude: [".gitignore", "README.md", "LICENSE"]
pygments: true
safe: false

# Google Analytics
